#!/bin/bash
#release version

if [[ "main.cpp" -nt "main.o" ]]
then
	g++ -c main.cpp
fi


if [[ "debugger.cpp" -nt "debugger.o" ]]
then
	g++ -c debugger.cpp
fi


if [[ "equation_solution.cpp" -nt "equation_solution.o" ]]
then
	g++ -c equation_solution.cpp
fi


if [[ "input_output.cpp" -nt "input_output.o" ]]
then
	g++ -c input_output.cpp
fi


if [[ "projectlib.cpp" -nt "projectlib.o" ]]
then
	g++ -c projectlib.cpp
fi


g++ main.o debugger.o equation_solution.o input_output.o projectlib.o -o program
